config/routes.rb
Rails.application.routes.draw do
  get 'mypage', to: 'users#show'
  get 'mypage/edit', to: 'users#edit', as: :edit_mypage
  patch 'mypage', to: 'users#update'
  root "homes#top"
  devise_for :users
   get "home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_one_attached :image
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @items = Item.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @item = current_user.items.build
  end

  def create 
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to @item, notice: "投稿が完了しました！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: "更新しました！"
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: "削除しました！"
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def authorize_user!
    redirect_to items_path, alert: "権限がありません！" unless @item.user == current_user
  end

  def item_params
    params.require(:item).permit(:title, :description, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def show
    @items = @user.items
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to mypage_path, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :image, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="w-100 text center">
      <h1 class="px-3 mx-auto">
        welcome to<br>
        <i class="fa-solid fa-arrows-rotate"></i>
        <strong>Nothing Wasted</strong>!
      </h1>
      <h3>A place to exchange and circulate!</h3>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      <div>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :title, "品物" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :image, "画像をアップロード" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "商品の詳細" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/items/edit.html.erb
<%= form_with(model: @item, local: true) do |f| %>
  <div class="mb-3">
    <%= f.label :image, "画像をアップロード" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
  <div class="mb-3">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :description, "内容" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/items/index.html.erb
<%= link_to "Browse Items", items_path, class: "btn btn-success mt-3" %>

<h1>All Items</h1>
<%= link_to "New Item", new_item_path, class: "btn btn-primary" %>
<ul class="list-group mt-3">
  <% @items.each do |item| %>
    <li class= "list-group-item">
      <strong><%= link_to item.title, item_path(item) %></strong>
      <smaill class="text-muted"> by <%= item.user.email %></small>
    </li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h2><%= action_name == "new" ? "New Item" : "Edit Item" %></h2>

<%= render "form", item: @item %>

<%= link_to "Back", items_path, class: "btn btn-link" %>

app/views/items/show.html.erb
<% if @item.image.attached? %>
  <%= image_tag @item.image, class: "img-fluid mb-3" %>
<% end %>

<h2><%= @item.title %></h2>
<p><%= @item.description %></p>
<p><small>Posted by <%= @item.user.email %></small></p>

<% if current_user == @item.user %>
  <%= link_to "Edit", edit_item_path(@item), class: "btn btn-outline-primary" %>
  <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
<% end %>

<%= link_to "Back", items_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nothingwasted</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3736542975.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container">
          <%= link_to "NothingWasted", root_path, class: "navbar-brand" %>

          <button class="navbar-toggler" type="button" data-bs-toggler="collapse" data-bs-target="#navbarContent">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ms-auto mb-2 mb-1g-0">
              <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link" %>
              </li>

              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "新規投稿", new_item_path, class: "nav-link" %>
                </li>

                <li class="nav-item">
                  <%= link_to "投稿一覧", items_path, class: "nav-link" %>
                </li>

                <li class="nav-item">
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>